import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { FileText, Loader2, Search } from "lucide-react";
import { getInspections } from "../services/inspectionService";
import StatusBadge from "../components/inspection/StatusBadge";

function Reports() {
  const [items, setItems] = useState([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { getInspections().then((d) => setItems(Array.isArray(d) ? d : d?.items || d?.validations || [])).catch((e) => setError(e?.response?.data?.detail || e?.message || "Unable to load reports.")).finally(() => setLoading(false)); }, []);
  const reports = useMemo(() => items.filter((x) => { const id = String(x.validation_id || x.inspection_id || ""); const s = String(x.overall_status || x.status || "PENDING").toUpperCase(); return id.toLowerCase().includes(search.toLowerCase()) && (status === "ALL" || s === status); }), [items, search, status]);
  return <div className="mx-auto w-full max-w-7xl space-y-6 pb-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">Reports</p><h1 className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">Inspection Reports</h1><p className="mt-2 text-sm text-slate-500">Generate and download reports for completed inspections.</p></div><div className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search validation ID..." className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="ALL">All statuses</option><option value="PASS">PASS</option><option value="REVIEW">REVIEW</option><option value="FAIL">FAIL</option></select></div>{loading ? <div className="flex justify-center p-12"><Loader2 className="animate-spin" /></div> : error ? <div className="p-8 text-center text-sm text-red-600">{error}</div> : reports.length === 0 ? <div className="p-10 text-center text-sm text-slate-500">No inspections available.</div> : <div className="divide-y divide-slate-100">{reports.map((r) => { const id = r.validation_id || r.inspection_id; const s = String(r.overall_status || r.status || "PENDING").toUpperCase(); return <div key={id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-100"><FileText size={18} className="text-slate-600" /></div><div><p className="break-all text-sm font-bold text-slate-900">{id}</p><p className="text-xs text-slate-500">Score: {r.validation_score ?? "—"}%</p></div></div><div className="flex items-center gap-3"><StatusBadge status={s} /><Link to={`/inspections/${id}/report`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">View Report</Link></div></div>; })}</div>}</div></div>;
}
export default Reports;
